### PR TITLE
DAT-70409 Expose basic line (package published)

### PR DESCRIPTION
**Pull request by crazypixel**
## Description
expose basic line component. a fix.

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Are you adding a new package?
- [ ] yes
- [x] no

### CODE REVIEW

**Review by kaufguy — APPROVED** [review]

**Comment by crazypixel** [comment]
cr-review

**Pull request merged**
