### PR TITLE
feature/DAT-70184 filters drop down

### PR DESCRIPTION
**Pull request by theblushingcrow**
## Short Description
Added capability in Filters component to replace the free text value field with dropdown for specific dimensions.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Are you adding a new package?
- [ ] yes
- [x ] no

## PR Checklist
- [x] I'm using the theme colors from styled-components and checked my component in dark mode as well
- [x] Add types (Prop-types / typescript)
- [x] Commit your changes
- [x] Run `npm version **` [minor, major, patch]. Commit changes
- [x] Run `npm run lib:build`. Commit changes
- [x] Run `npm run lib:version`. Commit changes
- [x] Push changes and open a pull request

### CODE REVIEW

**Review by itaydafna — APPROVED** [review]

**Review by crazypixel — COMMENTED** [review]
@theblushingcrow did you checked it with this new feature and without? is it backward compatible? will affect other apps that used it in the past?

**Comment by theblushingcrow** [comment]
> @theblushingcrow did you checked it with this new feature and without? is it backward compatible? will affect other apps that used it in the past?

yes, yes, and no, respectively :)

**Review by crazypixel — APPROVED** [review]

**Pull request merged**
