### PR TITLE
Dat 47318 app components basic table

### PR DESCRIPTION
**Pull request by daniel500tech**
## Table props:
- config {options, columnDefs}
- rowsData - array or object (map)

## Table options:
- rowRenderer
- headerRowRenderer
- emptyRenderer
- stickyHeader
- tableHeight
- rowClick
- searchable
- searchByFields
- pagination
- paginationPageSize
- paginationMax

## ColumnDefs options:
 - title
 - field 
 - width
 - justifyContent
 - cellRenderer
 - headerCellRenderer
 - valueGetter
 - headerValueGetter

### CODE REVIEW

**Comment by crazypixel** [comment]
@daniel500tech 
can you generate the docs again?
can you scroll to top when clicking on the pagination?

**Comment by crazypixel** [comment]
@daniel500tech 
can you update some props?

data - instead of rowsData.
rowRenderer
headerRowRenderer - what is this renderer for?
emptyRenderer - this is for no data state?
stickyHeader
tableHeight - what's the default?
rowClick - what is this prop for?
searchable
searchByFields - can you update to searchFields?
pagination
paginationPageSize - update to maxPageSize
paginationMax - let's remove this one and decide on a default one - 6 for example.

**Comment by daniel500tech** [comment]
@crazypixel 

1. isn’t `data` too generic? maybe change it to `rows`? BTW I took the naming from ag-grid
2. `headerRowRenderer` - is for rendering the table head row
3. `emptyRenderer` - yes, no data state
4. `tableHeight` - there’s no default, if you won’t pass height I’m not setting height at all
5. `rowClick` - callback that will be called when clicking a table row (click a row in the table and check out the console)
6. `searchByFields` - will change to `searchFields`
7. `paginationPageSize` - I wanted to name pagination related props with the `pagination` prefix (same as ag-grid)
8. `paginationMax` - why not letting the consumer to decide? The default is 3, I can change it to 6

**Comment by danielemesh** [comment]
@crazypixel @portons updated code according to your review, please review again.
Thanks!

**Pull request closed without merging**
